# Expansion landmarks - Europe (4 new) + Asia (6 new)
# 10 standard landmarks per country

EXPANSION_LANDMARKS_EA = {
    # ===== EUROPE (4 new countries) =====
    "turkey": [
        {"name": "Hagia Sophia", "description": "Byzantine masterpiece turned mosque with stunning dome in Istanbul.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Jun, Sep-Nov", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Cappadocia", "description": "Surreal landscape of fairy chimneys, cave dwellings and hot air balloons.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Jun, Sep-Nov", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Blue Mosque", "description": "Iconic Ottoman mosque with six minarets and blue Iznik tiles.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Ephesus", "description": "Well-preserved ancient Greek-Roman city with Library of Celsus.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Jun, Sep-Nov", "duration": "3-4 hours", "difficulty": "Easy"},
        {"name": "Pamukkale Travertines", "description": "Terraced thermal pools of white travertine limestone.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Jun, Sep-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Grand Bazaar Istanbul", "description": "One of the world's oldest and largest covered markets.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Topkapi Palace", "description": "Former residence of Ottoman sultans with treasury and harem.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "3-4 hours", "difficulty": "Easy"},
        {"name": "Antalya Old Town", "description": "Charming historic quarter with Ottoman houses and Roman harbor.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "3-4 hours", "difficulty": "Easy"},
        {"name": "Mount Nemrut", "description": "Summit with colossal stone statues of ancient Commagene gods.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Sumela Monastery", "description": "Ancient Greek Orthodox monastery carved into a steep cliff.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Half day", "difficulty": "Moderate"},
    ],
    "ireland": [
        {"name": "Cliffs of Moher", "description": "Sea cliffs reaching 214m above the Atlantic on Ireland's west coast.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Ring of Kerry", "description": "179km scenic drive through mountains, lakes and coastal villages.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Trinity College Library", "description": "Long Room housing the Book of Kells and 200,000 ancient texts.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Giants Causeway", "description": "40,000 interlocking basalt columns formed by volcanic activity.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Rock of Cashel", "description": "Dramatic medieval complex of Celtic art and architecture.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Killarney National Park", "description": "Pristine lakes, ancient oakwoods and red deer in County Kerry.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Blarney Castle", "description": "Medieval stronghold home to the legendary Blarney Stone.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Aran Islands", "description": "Remote islands preserving traditional Irish language and culture.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Guinness Storehouse", "description": "Seven-story experience at Dublin's St. James's Gate Brewery.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Connemara", "description": "Wild Atlantic landscape of bogs, mountains and Connemara ponies.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Full day", "difficulty": "Moderate"},
    ],
    "hungary": [
        {"name": "Hungarian Parliament", "description": "Neo-Gothic parliament on the Danube, Hungary's largest building.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Fishermans Bastion", "description": "Fairytale neo-Romanesque terrace with panoramic Budapest views.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Szechenyi Thermal Bath", "description": "Europe's largest medicinal bath complex in Budapest's City Park.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "3-4 hours", "difficulty": "Easy"},
        {"name": "Buda Castle", "description": "Historic castle complex on Castle Hill overlooking the Danube.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "3-4 hours", "difficulty": "Easy"},
        {"name": "Chain Bridge", "description": "First permanent bridge connecting Buda and Pest across the Danube.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "30 minutes", "difficulty": "Easy"},
        {"name": "Lake Balaton", "description": "Central Europe's largest lake, the Hungarian Sea.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Aug", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Eger Castle", "description": "Medieval fortress famous for its defense against Ottoman siege.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Hortobagyi National Park", "description": "UNESCO puszta landscape with traditional horsemen and wildlife.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Matthias Church", "description": "Gothic church on Castle Hill with colorful ceramic roof tiles.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Tokaj Wine Region", "description": "UNESCO wine region producing the famous sweet Tokaji Aszu wine.", "image_url": "", "images": [], "best_time_to_visit": "Sep-Oct", "duration": "Full day", "difficulty": "Easy"},
    ],
    "czech_republic": [
        {"name": "Prague Castle", "description": "Largest ancient castle complex in the world, seat of Czech rulers.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "3-4 hours", "difficulty": "Easy"},
        {"name": "Charles Bridge", "description": "Gothic stone bridge over the Vltava lined with Baroque statues.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Old Town Square Prague", "description": "Medieval square with Astronomical Clock and Gothic Tyn Church.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Cesky Krumlov", "description": "Fairytale medieval town with a castle complex and the Vltava River.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Kutna Hora Bone Church", "description": "Ossuary decorated with bones of 40,000 people, UNESCO site.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Karlovy Vary", "description": "Elegant spa town famous for hot springs and colonnades.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Petrin Hill", "description": "Hilltop park in Prague with observation tower and rose gardens.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Brno Underground", "description": "Labyrinth of medieval underground passages beneath the old town.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Moravian Karst Caves", "description": "Largest cave system in Czech Republic with underground river.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "3-4 hours", "difficulty": "Easy"},
        {"name": "Lednice Chateau", "description": "UNESCO neo-Gothic chateau with vast gardens and minaret.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Half day", "difficulty": "Easy"},
    ],

    # ===== ASIA (6 new countries) =====
    "laos": [
        {"name": "Luang Prabang Old Town", "description": "UNESCO town at the confluence of the Mekong and Nam Khan rivers.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Kuang Si Falls", "description": "Turquoise cascading waterfalls with natural swimming pools.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Vang Vieng", "description": "Dramatic karst landscape with river tubing and cave exploring.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Plain of Jars", "description": "Mysterious megalithic stone jars scattered across the plateau.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Wat Phou Temple", "description": "UNESCO Khmer Hindu temple complex predating Angkor Wat.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Pak Ou Caves", "description": "River caves filled with thousands of Buddha statues.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "Half day", "difficulty": "Easy"},
        {"name": "That Luang Stupa", "description": "National symbol of Laos, a gold-covered Buddhist stupa.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Si Phan Don (4000 Islands)", "description": "River archipelago in the Mekong with waterfalls and dolphins.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Bolaven Plateau", "description": "Highland plateau with coffee plantations and stunning waterfalls.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Patuxai Victory Monument", "description": "Vientiane's Arc de Triomphe-inspired war memorial with city views.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "1 hour", "difficulty": "Easy"},
    ],
    "mongolia": [
        {"name": "Gobi Desert", "description": "Vast desert with sand dunes, dinosaur fossils and nomadic camps.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "3-5 days", "difficulty": "Moderate"},
        {"name": "Genghis Khan Statue Complex", "description": "40m stainless steel equestrian statue of Genghis Khan.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Khuvsgul Lake", "description": "Mongolia's largest freshwater lake, the younger sister of Baikal.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "2-3 days", "difficulty": "Moderate"},
        {"name": "Terelj National Park", "description": "Scenic park with rock formations and traditional ger camps.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Erdene Zuu Monastery", "description": "First Buddhist monastery in Mongolia surrounded by 108 stupas.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Flaming Cliffs Bayanzag", "description": "Red sandstone cliffs where the first dinosaur eggs were discovered.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Orkhon Valley", "description": "UNESCO cultural landscape with ancient capital ruins and waterfalls.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "2-3 days", "difficulty": "Moderate"},
        {"name": "Gandantegchinlen Monastery", "description": "Active Buddhist monastery in Ulaanbaatar with 26m Janraisig statue.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Khongoryn Els Sand Dunes", "description": "Singing Dunes stretching 100km in the Gobi, up to 300m high.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Altai Tavan Bogd Mountains", "description": "Five sacred peaks on the border of Mongolia, Russia, and China with glaciers and ancient Turkic petroglyphs.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "2-3 days", "difficulty": "Moderate"},
    ],
    "bhutan": [
        {"name": "Tigers Nest Monastery", "description": "Sacred clifftop monastery perched 3,120m above the Paro Valley.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Punakha Dzong", "description": "Majestic fortress at the confluence of two rivers.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Tashichho Dzong", "description": "Seat of Bhutan's government with striking traditional architecture.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Dochula Pass", "description": "Mountain pass with 108 memorial stupas and Himalayan panoramas.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Feb", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Gangtey Valley", "description": "Glacial valley home to endangered black-necked cranes.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Feb", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Buddha Dordenma Statue", "description": "52m tall gilded bronze Buddha statue overlooking Thimphu.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Bumthang Valley Temples", "description": "Spiritual heartland of Bhutan with ancient temples and festivals.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Chele La Pass", "description": "Highest motorable pass in Bhutan at 3,988m with prayer flags.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Rinpung Dzong", "description": "Fortress monastery overlooking the Paro valley.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "National Museum of Bhutan", "description": "Round watchtower museum with art, textiles and Bhutanese history.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
    ],
    "georgia": [
        {"name": "Gergeti Trinity Church", "description": "14th-century church beneath Mount Kazbek at 2,170m elevation.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Old Town Tbilisi", "description": "Historic district with sulphur baths, churches and winding alleys.", "image_url": "", "images": [], "best_time_to_visit": "May-Jun, Sep-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Vardzia Cave Monastery", "description": "Medieval cave monastery carved into a cliff face with 6,000 rooms.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Svaneti Towers", "description": "Medieval defensive towers in the high Caucasus village of Ushguli.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "2-3 days", "difficulty": "Moderate"},
        {"name": "Narikala Fortress", "description": "Ancient fortress overlooking Tbilisi with panoramic city views.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Jvari Monastery", "description": "6th-century monastery overlooking the confluence of two rivers.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Kakheti Wine Region", "description": "Georgia's premier wine region with 8,000 years of winemaking.", "image_url": "", "images": [], "best_time_to_visit": "Sep-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Prometheus Cave", "description": "Spectacular limestone cave with illuminated stalactites.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Bridge of Peace Tbilisi", "description": "Futuristic glass and steel pedestrian bridge over the Mtkvari River.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "30 minutes", "difficulty": "Easy"},
        {"name": "Uplistsikhe Cave Town", "description": "Ancient rock-hewn town dating back to the early Iron Age.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 hours", "difficulty": "Easy"},
    ],
    "uzbekistan": [
        {"name": "Registan Square", "description": "Iconic ensemble of three madrasas, jewel of the Silk Road.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Bibi-Khanym Mosque", "description": "Monumental 15th-century mosque built by Tamerlane in Samarkand.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Itchan Kala Khiva", "description": "UNESCO inner walled city of Khiva with turquoise minarets.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Shah-i-Zinda Necropolis", "description": "Avenue of mausoleums with the finest Islamic tile work.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Bukhara Old Town", "description": "2,500-year-old Silk Road city with over 140 architectural monuments.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Gur-e-Amir Mausoleum", "description": "Tamerlane's mausoleum with stunning fluted blue dome.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Aral Sea Ship Graveyard", "description": "Haunting remnants of the former fourth-largest lake in the world.", "image_url": "", "images": [], "best_time_to_visit": "Apr-May, Sep-Oct", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Kalyan Minaret", "description": "47m 12th-century Tower of Death that impressed Genghis Khan.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Chorsu Bazaar Tashkent", "description": "Ancient domed bazaar with vibrant stalls in Tashkent's old town.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Savitsky Museum Nukus", "description": "Hidden gem with world's second-largest Russian avant-garde collection.", "image_url": "", "images": [], "best_time_to_visit": "Mar-May, Sep-Nov", "duration": "2-3 hours", "difficulty": "Easy"},
    ],
    "kyrgyzstan": [
        {"name": "Issyk-Kul Lake", "description": "World's second-largest alpine lake surrounded by snow-capped peaks.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Song-Kol Lake", "description": "High-altitude alpine lake at 3,016m with yurt camps and horsemen.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "2-3 days", "difficulty": "Moderate"},
        {"name": "Burana Tower", "description": "11th-century Karakhanid minaret remnant on the Silk Road.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Ala-Archa National Park", "description": "Alpine park in the Tien Shan mountains near Bishkek.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Jeti-Oguz Valley", "description": "Valley of Seven Bulls with red sandstone rock formations.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Skazka Canyon", "description": "Fairytale Canyon with surreal eroded red rock formations.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Osh Bazaar", "description": "Central Asia's largest and most vibrant outdoor market.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Sulayman Mountain", "description": "UNESCO sacred mountain in Osh with panoramic views.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 hours", "difficulty": "Moderate"},
        {"name": "Arslanbob Walnut Forest", "description": "World's largest natural walnut forest with stunning mountain scenery.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Tash Rabat Caravanserai", "description": "15th-century stone Silk Road caravanserai at 3,200m altitude.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Moderate"},
    ],
}
