# Expansion landmarks - Americas (4 new) + Oceania (10 new incl. Hawaii)
# 10 standard landmarks per country

EXPANSION_LANDMARKS_AO = {
    # ===== AMERICAS (4 new countries) =====
    "uruguay": [
        {"name": "Colonia del Sacramento", "description": "UNESCO colonial quarter with cobblestone streets and Portuguese ruins.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Apr", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Punta del Este", "description": "Glamorous seaside resort with La Mano sculpture on the beach.", "image_url": "", "images": [], "best_time_to_visit": "Dec-Mar", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Montevideo Old Town", "description": "Charming Ciudad Vieja with Art Deco architecture and markets.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Apr", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Cabo Polonio", "description": "Off-grid beach village with sea lions and dunes, no electricity.", "image_url": "", "images": [], "best_time_to_visit": "Dec-Mar", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Mercado del Puerto", "description": "Historic port market in Montevideo with grilled meat and live music.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Jose Ignacio Lighthouse", "description": "Picturesque lighthouse in an exclusive beach village.", "image_url": "", "images": [], "best_time_to_visit": "Dec-Mar", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Salto Hot Springs", "description": "Natural thermal baths on the Uruguay River.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Palacio Salvo", "description": "Art Deco landmark building dominating Montevideo's skyline.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1 hour", "difficulty": "Easy"},
        {"name": "Quebrada de los Cuervos", "description": "Protected area with a stunning river gorge and diverse wildlife.", "image_url": "", "images": [], "best_time_to_visit": "Sep-Apr", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Casapueblo", "description": "Whitewashed building by artist Paez Vilaro, now a museum and hotel.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
    ],
    "bolivia": [
        {"name": "Salar de Uyuni", "description": "World's largest salt flat creating a mirror effect in rainy season.", "image_url": "", "images": [], "best_time_to_visit": "Dec-Apr (mirror), May-Nov (dry)", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Lake Titicaca Bolivia", "description": "Sacred lake with Isla del Sol and ancient Inca ruins.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "La Paz Witches Market", "description": "Mercado de las Brujas selling traditional remedies and charms.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Death Road (Yungas Road)", "description": "World's most dangerous road now a thrilling mountain biking route.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Tiwanaku Ruins", "description": "Pre-Columbian archaeological site of the Tiwanaku civilization.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Sucre White City", "description": "UNESCO constitutional capital with colonial whitewashed buildings.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Madidi National Park", "description": "One of the most biodiverse places on Earth in the Amazon basin.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 days", "difficulty": "Moderate"},
        {"name": "Potosi Silver Mines", "description": "Historic silver mines that once made Potosi the richest city in the world.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Eduardo Avaroa Reserve", "description": "Surreal high-altitude landscape with colored lagoons and flamingos.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Valle de la Luna La Paz", "description": "Eroded clay formations creating a moonlike landscape near La Paz.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
    ],
    "belize": [
        {"name": "Great Blue Hole", "description": "Giant marine sinkhole, one of the world's best diving sites.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Jun", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Xunantunich Mayan Ruins", "description": "Ancient Maya city with El Castillo pyramid overlooking the jungle.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Caye Caulker", "description": "Laid-back Caribbean island with the motto Go Slow.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Actun Tunichil Muknal Cave", "description": "Sacred Maya cave with crystal-encrusted human remains.", "image_url": "", "images": [], "best_time_to_visit": "Feb-May", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Belize Barrier Reef", "description": "UNESCO second-largest barrier reef system in the world.", "image_url": "", "images": [], "best_time_to_visit": "Nov-May", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Lamanai Maya Ruins", "description": "Jungle-surrounded Maya site accessible only by river boat.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Cockscomb Basin Wildlife Sanctuary", "description": "World's first jaguar preserve in tropical forest.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Placencia Beach", "description": "16-mile peninsula with the narrowest main street in the world.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Caracol Maya City", "description": "Largest Maya site in Belize with the tallest man-made structure.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Hol Chan Marine Reserve", "description": "Marine reserve with nurse sharks, rays and tropical fish.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
    ],
    "saint_lucia": [
        {"name": "The Pitons", "description": "Iconic twin volcanic peaks rising dramatically from the sea.", "image_url": "", "images": [], "best_time_to_visit": "Dec-May", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Sulphur Springs", "description": "World's only drive-in volcano with bubbling mud baths.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Pigeon Island National Park", "description": "Historic military complex with panoramic views of Martinique.", "image_url": "", "images": [], "best_time_to_visit": "Dec-May", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Marigot Bay", "description": "Hurricane hole bay once called the most beautiful in the Caribbean.", "image_url": "", "images": [], "best_time_to_visit": "Dec-May", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Anse Chastanet Beach", "description": "Volcanic sand beach at the base of the Pitons with coral reef.", "image_url": "", "images": [], "best_time_to_visit": "Dec-May", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Diamond Falls Botanical Gardens", "description": "Tropical gardens with a waterfall that changes color.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Soufriere Town", "description": "Charming old French colonial town beneath the Pitons.", "image_url": "", "images": [], "best_time_to_visit": "Dec-May", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Toraille Waterfall", "description": "50-foot waterfall tumbling into a garden pool.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1 hour", "difficulty": "Easy"},
        {"name": "Castries Market", "description": "Vibrant Saturday market with spices, crafts and local food.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Tet Paul Nature Trail", "description": "Short trail with the best panoramic views of the Pitons.", "image_url": "", "images": [], "best_time_to_visit": "Dec-May", "duration": "1-2 hours", "difficulty": "Easy"},
    ],

    # ===== OCEANIA & ISLAND PARADISES (10 new: Hawaii + 9 new island countries) =====
    "hawaii": [
        {"name": "Waikiki Beach", "description": "World-famous beach with Diamond Head backdrop in Honolulu.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Na Pali Coast", "description": "Dramatic fluted cliffs along Kauai's northwestern shore.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Hawaii Volcanoes National Park", "description": "Active volcanoes Kilauea and Mauna Loa on Big Island.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Pearl Harbor Memorial", "description": "USS Arizona Memorial honoring the 1941 attack.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Haleakala Crater", "description": "Massive volcanic crater on Maui, above the clouds at 3,055m.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Road to Hana", "description": "Winding scenic drive through rainforest, waterfalls and bridges.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Kalalau Trail", "description": "Challenging 18km coastal trail along Kauai's Na Pali Coast.", "image_url": "", "images": [], "best_time_to_visit": "May-Sep", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Molokini Crater", "description": "Crescent-shaped volcanic crater ideal for snorkeling and diving.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Diamond Head", "description": "Iconic volcanic crater with panoramic views of Honolulu.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Moderate"},
        {"name": "Waimea Canyon", "description": "Grand Canyon of the Pacific with colorful 900m deep gorge.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Half day", "difficulty": "Easy"},
    ],
    "madagascar": [
        {"name": "Avenue of the Baobabs", "description": "Iconic dirt road lined with 800-year-old towering baobab trees.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Tsingy de Bemaraha", "description": "UNESCO razor-sharp limestone pinnacle forest unique to Madagascar.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Nosy Be Island", "description": "Tropical island paradise with ylang-ylang plantations and lemurs.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Isalo National Park", "description": "Sandstone massif with canyons, natural pools and lemurs.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "1-2 days", "difficulty": "Moderate"},
        {"name": "Andasibe-Mantadia National Park", "description": "Rainforest home to the Indri, the world's largest lemur.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Ranomafana National Park", "description": "Cloud forest with hot springs and rare golden bamboo lemur.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Ile Sainte-Marie", "description": "Former pirate haven with whale watching and colonial cemetery.", "image_url": "", "images": [], "best_time_to_visit": "Jul-Sep (whales)", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Rova of Antananarivo", "description": "Royal palace complex on the highest hill of the capital.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Kirindy Forest", "description": "Dry deciduous forest with the elusive fossa and night lemurs.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Ifaty Coral Reef", "description": "Offshore coral reef with diverse marine life and spiny forest.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "Full day", "difficulty": "Easy"},
    ],
    "cape_verde": [
        {"name": "Pico do Fogo Volcano", "description": "Active stratovolcano rising to 2,829m on Fogo island.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Jun", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Santa Maria Beach Sal", "description": "Long golden sand beach with crystal-clear waters on Sal island.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Mindelo Harbor", "description": "Vibrant cultural capital with carnival and live music scene.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Cha das Caldeiras", "description": "Village inside Fogo's volcanic crater with unique wine production.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Jun", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Cidade Velha", "description": "UNESCO first European colonial settlement in the tropics.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Santo Antao Hiking Trails", "description": "Dramatic volcanic island with world-class hiking through valleys.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Jun", "duration": "1-3 days", "difficulty": "Moderate"},
        {"name": "Sal Rei Boa Vista", "description": "Charming town on Boa Vista with shipwrecks and sand dunes.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Buracona Blue Eye", "description": "Natural lava pool with mesmerizing blue light effect.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Praia de Chaves", "description": "Spectacular 5km white sand beach on Boa Vista's west coast.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Paul Valley Santo Antao", "description": "Verdant valley with sugarcane terraces and grog distilleries.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Jun", "duration": "Full day", "difficulty": "Moderate"},
    ],
    "papua_new_guinea": [
        {"name": "Kokoda Track", "description": "96km historic WWII trail through jungle mountains.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "6-10 days", "difficulty": "Challenging"},
        {"name": "Sepik River", "description": "PNG's longest river with indigenous art and spirit houses.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "3-5 days", "difficulty": "Moderate"},
        {"name": "Mount Wilhelm", "description": "PNG's highest peak at 4,509m with stunning sunrise views.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 days", "difficulty": "Challenging"},
        {"name": "Rabaul Volcano", "description": "Twin volcanoes overlooking the submerged caldera harbor.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Tufi Fjords", "description": "Tropical fjords with diving, snorkeling and indigenous villages.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Goroka Show", "description": "Annual cultural festival with 100+ tribes in traditional dress.", "image_url": "", "images": [], "best_time_to_visit": "Sep (festival)", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Kimbe Bay", "description": "World-class reef diving with 860 species of reef fish.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Tari Valley Huli Wigmen", "description": "Highlands valley home to the Huli tribe with ceremonial wigs.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Milne Bay WWII Wrecks", "description": "Underwater WWII aircraft and ship wrecks for diving.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "1-2 days", "difficulty": "Moderate"},
        {"name": "Madang Lagoon", "description": "Beautiful coastal town known as the prettiest in the Pacific.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "1-2 days", "difficulty": "Easy"},
    ],
    "palau": [
        {"name": "Jellyfish Lake", "description": "Marine lake with millions of non-stinging golden jellyfish.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Rock Islands", "description": "UNESCO archipelago of 445 uninhabited limestone islands.", "image_url": "", "images": [], "best_time_to_visit": "Oct-May", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Blue Corner Wall Dive", "description": "World-famous wall dive with sharks, mantas and schooling fish.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Milky Way Lagoon", "description": "Turquoise lagoon with white mud said to have rejuvenating properties.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Ngardmau Waterfall", "description": "Palau's largest waterfall reached by jungle trail.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Belau National Museum", "description": "Oldest museum in Micronesia with Palauan artifacts and bai.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "German Channel", "description": "Man-made channel famous for manta ray cleaning station.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Peleliu Island WWII Sites", "description": "Former WWII battleground with tanks, tunnels and memorials.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Long Lake", "description": "Pristine freshwater lake surrounded by dense jungle on Babeldaob.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Ngerulmud Capitol", "description": "World's least populated national capital with modern congress building.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
    ],
    "solomon_islands": [
        {"name": "Guadalcanal WWII Sites", "description": "Major WWII battlefield sites and memorials from Pacific War.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Marovo Lagoon", "description": "World's largest saltwater lagoon with pristine coral reefs.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Tetepare Island", "description": "Largest uninhabited island in the South Pacific with leatherback turtles.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "2-3 days", "difficulty": "Moderate"},
        {"name": "Bonegi Beach Wrecks", "description": "WWII Japanese transport ship wrecks accessible by snorkeling.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Skull Island", "description": "Sacred island with ancient headhunting shrines and artifacts.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Kennedy Island", "description": "Island where JFK swam ashore after his PT boat was sunk.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Rennell Island", "description": "UNESCO raised coral atoll with Lake Tegano, largest in Pacific.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "2-3 days", "difficulty": "Moderate"},
        {"name": "Honiara Central Market", "description": "Bustling main market with betel nut, fish and local produce.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Uepi Island Diving", "description": "World-class dive resort with pristine drop-offs and coral gardens.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Kolombangara Volcano", "description": "Dormant stratovolcano with hiking through pristine rainforest.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Challenging"},
    ],
    "new_caledonia": [
        {"name": "Heart of Voh", "description": "Natural heart-shaped clearing in mangroves, iconic aerial view.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Isle of Pines", "description": "The closest island to paradise with towering araucaria pines.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "New Caledonia Barrier Reef", "description": "UNESCO second-longest double-barrier reef in the world.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Tjibaou Cultural Centre", "description": "Renzo Piano-designed center celebrating Kanak culture.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Amedee Lighthouse Island", "description": "56m lighthouse on a tiny islet with snorkeling and glass-bottom boats.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Blue River Provincial Park", "description": "Unique red-soil park with endemic plants and drowned forest.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Lifou Island", "description": "Loyalty island with massive sea cliffs and vanilla plantations.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Noumea Aquarium", "description": "Renowned aquarium showcasing New Caledonia's unique marine life.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Prony Bay", "description": "Secluded bay with underwater hot springs and nickel mine history.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Hienghene Rock Formations", "description": "Dramatic limestone formations including the iconic Sphinx rock.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Easy"},
    ],
    "guam": [
        {"name": "Two Lovers Point", "description": "Dramatic cliff overlook with panoramic views of Tumon Bay.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Tumon Bay Beach", "description": "Guam's most popular beach with crystal-clear turquoise waters.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "War in the Pacific Park", "description": "National park preserving WWII battle sites and memorials.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Fort Nuestra Senora de la Soledad", "description": "Spanish colonial fort with views of Umatac Bay.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Talofofo Falls", "description": "Three-tiered waterfall in lush jungle with cable car access.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Cocos Island", "description": "Small island off Guam's southern tip with snorkeling.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Latte Stone Park", "description": "Ancient Chamorro stone pillars, symbol of Guam's heritage.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "30 minutes", "difficulty": "Easy"},
        {"name": "Ritidian Point", "description": "Pristine wildlife refuge with stunning beach and ancient cave art.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Chamorro Village Night Market", "description": "Wednesday night market with local food, crafts and entertainment.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Cetti Bay Overlook", "description": "Dramatic coastal viewpoint on Guam's rugged southern shore.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1 hour", "difficulty": "Easy"},
    ],
    "comoros": [
        {"name": "Mount Karthala", "description": "Active volcano with one of the world's largest craters.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Moheli Marine Park", "description": "First marine park in Comoros with sea turtles and humpback whales.", "image_url": "", "images": [], "best_time_to_visit": "Jul-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Moroni Old Friday Mosque", "description": "Historic mosque in the capital with Arabic calligraphy carvings.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1 hour", "difficulty": "Easy"},
        {"name": "Itsandra Beach", "description": "Black volcanic sand beach near Moroni with sunset views.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Livingstone Bat Colony", "description": "Critically endangered Livingstone's fruit bats on Anjouan.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Lac Sale", "description": "Unique crater lake surrounded by dense tropical vegetation.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Chomoni Beach", "description": "Secluded white sand beach on Grande Comore's east coast.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Mutsamudu Medina", "description": "Old Arab quarter with narrow streets and a Sultan's palace.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Coelacanth Discovery Site", "description": "Waters where the living fossil coelacanth was rediscovered.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Dziani Dzaha Crater Lake", "description": "Emerald green volcanic lake on Mayotte island.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "2-3 hours", "difficulty": "Easy"},
    ],
    "reunion": [
        {"name": "Piton de la Fournaise", "description": "One of the world's most active volcanoes with lunar landscape.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Cirque de Mafate", "description": "Remote caldera accessible only by foot or helicopter.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "1-3 days", "difficulty": "Challenging"},
        {"name": "Cirque de Cilaos", "description": "Dramatic caldera with thermal springs and lentil farming.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Piton des Neiges", "description": "Highest peak in the Indian Ocean at 3,070m.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Plage de lEtang-Sale", "description": "Dramatic black volcanic sand beach on the west coast.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Kelonia Sea Turtle Observatory", "description": "Conservation center for sea turtles with educational exhibits.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Saint-Denis Market", "description": "Vibrant Creole market with spices, vanilla and tropical fruits.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Trou de Fer", "description": "Iron Hole - a spectacular 300m deep waterfall canyon.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Grand Anse Beach", "description": "Wild and beautiful beach on the untamed south coast.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Cirque de Salazie", "description": "Lush green caldera with waterfall village of Hell-Bourg.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Easy"},
    ],
}
