# Expansion landmarks - Africa (12 new countries)
# 10 standard landmarks per country

EXPANSION_LANDMARKS_AF = {
    "ghana": [
        {"name": "Cape Coast Castle", "description": "UNESCO-listed slave trading fort on Ghana's Atlantic coast.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Kakum National Park", "description": "Rainforest canopy walkway 30m above the ground.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Elmina Castle", "description": "Oldest European building in sub-Saharan Africa, built in 1482.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Mole National Park", "description": "Ghana's largest wildlife refuge with elephants and antelopes.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Kwame Nkrumah Memorial Park", "description": "Mausoleum and park honoring Ghana's first president.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Wli Waterfalls", "description": "Highest waterfall in West Africa in the Volta Region.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Oct", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Larabanga Mosque", "description": "One of the oldest mosques in West Africa, built in Sudanese style.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Labadi Beach Accra", "description": "Popular beach with lively atmosphere, music and local food.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Ashanti Kingdom Palace", "description": "UNESCO traditional buildings of the Ashanti Kingdom in Kumasi.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Lake Bosomtwe", "description": "Sacred natural crater lake, only meteorite impact lake in West Africa.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Half day", "difficulty": "Easy"},
    ],
    "rwanda": [
        {"name": "Volcanoes National Park", "description": "Home to endangered mountain gorillas in the Virunga Mountains.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Kigali Genocide Memorial", "description": "Moving memorial to the 1994 genocide with over 250,000 victims.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Lake Kivu", "description": "One of Africa's Great Lakes with islands and hot springs.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Nyungwe Forest", "description": "Ancient montane rainforest with chimpanzees and canopy walk.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Akagera National Park", "description": "Big Five safari park with savanna, lakes and papyrus swamps.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Kings Palace Museum Nyanza", "description": "Reconstructed traditional royal residence of Rwandan kings.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Musanze Caves", "description": "Volcanic lava tube caves stretching over 2km underground.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Twin Lakes Burera and Ruhondo", "description": "Stunning volcanic twin lakes surrounded by green terraced hills.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Inema Arts Center", "description": "Vibrant contemporary art gallery and creative space in Kigali.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Mount Bisoke Crater Lake", "description": "Volcanic crater lake at 3,711m with stunning views.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Challenging"},
    ],
    "uganda": [
        {"name": "Bwindi Impenetrable Forest", "description": "UNESCO site with half the world's mountain gorilla population.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep, Dec-Feb", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Murchison Falls", "description": "The world's most powerful waterfall squeezing through a 7m gap.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Source of the Nile Jinja", "description": "Where the White Nile begins its journey from Lake Victoria.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Queen Elizabeth National Park", "description": "Diverse park with tree-climbing lions and Kazinga Channel.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Rwenzori Mountains", "description": "Mountains of the Moon with glaciers and endemic species.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep, Dec-Feb", "duration": "3-7 days", "difficulty": "Challenging"},
        {"name": "Kibale Forest Chimps", "description": "Primate capital of the world with 13 primate species.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Lake Bunyonyi", "description": "Africa's second-deepest lake with 29 islands and terraced hills.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Kasubi Tombs", "description": "UNESCO burial grounds of Buganda kings, rebuilt after 2010 fire.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Sipi Falls", "description": "Three stunning waterfalls on the edge of Mount Elgon.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Ssese Islands", "description": "84 tropical islands in Lake Victoria with pristine beaches.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Sep", "duration": "2-3 days", "difficulty": "Easy"},
    ],
    "ethiopia": [
        {"name": "Rock-Hewn Churches of Lalibela", "description": "11 medieval monolithic churches carved from solid rock.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Simien Mountains", "description": "UNESCO dramatic landscape with endemic Gelada baboons.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "3-5 days", "difficulty": "Challenging"},
        {"name": "Danakil Depression", "description": "One of the hottest places on Earth with alien-like sulfur springs.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "2-3 days", "difficulty": "Challenging"},
        {"name": "Fasil Ghebbi (Gondar Castle)", "description": "Royal enclosure of medieval castles, the Camelot of Africa.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Blue Nile Falls", "description": "Smoking Water - one of Africa's most spectacular waterfalls.", "image_url": "", "images": [], "best_time_to_visit": "Sep-Nov", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Omo Valley Tribes", "description": "Cultural immersion with indigenous tribes preserving ancient traditions.", "image_url": "", "images": [], "best_time_to_visit": "Sep-Mar", "duration": "3-5 days", "difficulty": "Moderate"},
        {"name": "Harar Jugol", "description": "UNESCO walled city with 82 mosques and wild hyena feeding.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Lake Tana Monasteries", "description": "Island monasteries on Ethiopia's largest lake, source of Blue Nile.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Axum Obelisks", "description": "Ancient stelae marking the heart of the Aksumite Empire.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Bale Mountains National Park", "description": "Afro-alpine habitat with endemic Ethiopian wolf.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "2-3 days", "difficulty": "Moderate"},
    ],
    "senegal": [
        {"name": "Goree Island", "description": "UNESCO island symbolizing the Atlantic slave trade.", "image_url": "", "images": [], "best_time_to_visit": "Nov-May", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Lac Rose (Pink Lake)", "description": "Salt lake that turns pink from Dunaliella algae.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Jun", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Djoudj Bird Sanctuary", "description": "UNESCO wetland hosting over 1.5 million migratory birds.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Apr", "duration": "Full day", "difficulty": "Easy"},
        {"name": "African Renaissance Monument", "description": "49m bronze statue overlooking Dakar, tallest in Africa.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Niokolo-Koba National Park", "description": "UNESCO park with lions, chimpanzees and hippos.", "image_url": "", "images": [], "best_time_to_visit": "Dec-May", "duration": "1-2 days", "difficulty": "Moderate"},
        {"name": "Saint-Louis Historic City", "description": "UNESCO colonial city at the mouth of the Senegal River.", "image_url": "", "images": [], "best_time_to_visit": "Nov-May", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Saly Beach Resort", "description": "Popular resort area with golden beaches on the Petite Cote.", "image_url": "", "images": [], "best_time_to_visit": "Nov-May", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Casamance Region", "description": "Lush southern region with mangroves, sacred forests and culture.", "image_url": "", "images": [], "best_time_to_visit": "Nov-May", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Grande Mosquee de Touba", "description": "One of Africa's largest mosques, holy city of the Mouride brotherhood.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Bandia Wildlife Reserve", "description": "Private reserve near Dakar with giraffes, rhinos and antelopes.", "image_url": "", "images": [], "best_time_to_visit": "Nov-May", "duration": "Half day", "difficulty": "Easy"},
    ],
    "zimbabwe": [
        {"name": "Victoria Falls", "description": "The world's largest curtain of falling water, the Smoke that Thunders.", "image_url": "", "images": [], "best_time_to_visit": "Feb-May", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Great Zimbabwe Ruins", "description": "Medieval stone city ruins, largest ancient structure in sub-Saharan Africa.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Hwange National Park", "description": "Zimbabwe's largest game reserve with huge elephant herds.", "image_url": "", "images": [], "best_time_to_visit": "Jul-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Matobo Hills", "description": "UNESCO granite hills with San rock art and black eagle habitat.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Lake Kariba", "description": "One of the world's largest man-made lakes with houseboat safaris.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Mana Pools National Park", "description": "UNESCO park on the Zambezi with walking safaris among elephants.", "image_url": "", "images": [], "best_time_to_visit": "Jul-Oct", "duration": "2-3 days", "difficulty": "Moderate"},
        {"name": "Balancing Rocks Epworth", "description": "Iconic granite formations that appear to defy gravity.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Chimanimani Mountains", "description": "Misty mountain range perfect for hiking and waterfalls.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "1-3 days", "difficulty": "Moderate"},
        {"name": "Khami Ruins", "description": "UNESCO ruins of the 15th-century capital of the Torwa dynasty.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Eastern Highlands", "description": "Scenic mountain region with forests, waterfalls and tea estates.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Oct", "duration": "2-3 days", "difficulty": "Easy"},
    ],
    "zambia": [
        {"name": "Victoria Falls Zambia Side", "description": "View the Smoke that Thunders from the Zambian side with spray walk.", "image_url": "", "images": [], "best_time_to_visit": "Feb-May", "duration": "Half day", "difficulty": "Easy"},
        {"name": "South Luangwa National Park", "description": "Premier safari park known for walking safaris and leopard sightings.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Oct", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Lower Zambezi National Park", "description": "Unfenced park with canoe safaris along the mighty Zambezi.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Lake Bangweulu Wetlands", "description": "Vast wetland system with shoebill storks and black lechwe.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Kafue National Park", "description": "Zambia's largest and oldest national park with vast wilderness.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Oct", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Livingstone Museum", "description": "Zambia's national museum with David Livingstone memorabilia.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Kasanka National Park Bat Migration", "description": "World's largest mammal migration - 10 million straw-colored fruit bats.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Dec", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Shiwa Ngandu Manor", "description": "Surreal English country house in the African bush.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Bangweulu Swamps", "description": "Pristine wetland ecosystem home to rare shoebill stork.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Oct", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Kundalila Falls", "description": "Beautiful 67m waterfall near Serenje with natural swimming pool.", "image_url": "", "images": [], "best_time_to_visit": "Mar-Jul", "duration": "Half day", "difficulty": "Moderate"},
    ],
    "mozambique": [
        {"name": "Bazaruto Archipelago", "description": "Pristine island chain with turquoise waters and dugongs.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Island of Mozambique", "description": "UNESCO fortified island with Portuguese colonial and Islamic heritage.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Tofo Beach", "description": "World-class diving spot with whale sharks and manta rays.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Gorongosa National Park", "description": "Restored biodiversity hotspot, Africa's conservation success story.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Quirimbas Archipelago", "description": "Remote northern islands with pristine reefs and colonial ruins.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Maputo Central Market", "description": "Vibrant market in an Art Nouveau iron building from 1901.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Vilankulo", "description": "Gateway town to Bazaruto with dhow sailing and beach culture.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Cahora Bassa Dam", "description": "One of Africa's largest dams on the Zambezi with stunning gorge.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Maputo Special Reserve", "description": "Coastal reserve with elephants, dolphins and pristine beaches.", "image_url": "", "images": [], "best_time_to_visit": "Apr-Nov", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Fortress of Sao Sebastiao", "description": "16th-century Portuguese fort on the Island of Mozambique.", "image_url": "", "images": [], "best_time_to_visit": "May-Nov", "duration": "1-2 hours", "difficulty": "Easy"},
    ],
    "ivory_coast": [
        {"name": "Basilica of Our Lady of Peace", "description": "World's largest church, inspired by St. Peter's Basilica.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Tai National Park", "description": "UNESCO primary tropical rainforest with chimpanzees and pygmy hippos.", "image_url": "", "images": [], "best_time_to_visit": "Dec-Mar", "duration": "1-2 days", "difficulty": "Moderate"},
        {"name": "Grand-Bassam Historic Town", "description": "UNESCO colonial capital with Afro-European architecture.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Comoe National Park", "description": "UNESCO savanna park, one of the largest protected areas in West Africa.", "image_url": "", "images": [], "best_time_to_visit": "Dec-Mar", "duration": "1-2 days", "difficulty": "Moderate"},
        {"name": "Abidjan Plateau District", "description": "Modern skyline district with Le Plateau's business towers.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Mount Nimba Strict Nature Reserve", "description": "UNESCO reserve shared with Guinea and Liberia, rich biodiversity.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Man Region Stilt Dancers", "description": "Western region famous for traditional stilt dancing and mask culture.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Banco National Park", "description": "Tropical rainforest park within Abidjan city limits.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Assinie Beach", "description": "Popular palm-lined beach resort area east of Abidjan.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Mosque of Kong", "description": "Historic Sudanese-style mud mosque from the 17th century.", "image_url": "", "images": [], "best_time_to_visit": "Nov-Mar", "duration": "1-2 hours", "difficulty": "Easy"},
    ],
    "malawi": [
        {"name": "Lake Malawi National Park", "description": "UNESCO lake with more fish species than any other lake on Earth.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Cape Maclear", "description": "Paradise beach on Lake Malawi with snorkeling and kayaking.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Majete Wildlife Reserve", "description": "Restored Big Five reserve, a major conservation success.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Mount Mulanje", "description": "Massive granite massif known as the Island in the Sky.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-4 days", "difficulty": "Challenging"},
        {"name": "Liwonde National Park", "description": "Scenic park along the Shire River with elephants and hippos.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Nkhotakota Wildlife Reserve", "description": "Malawi's oldest and largest reserve, home to relocated elephants.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Likoma Island", "description": "Remote island with a massive cathedral and pristine lake waters.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "2-3 days", "difficulty": "Easy"},
        {"name": "Zomba Plateau", "description": "Cool highland plateau with forests, streams and panoramic views.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Chongoni Rock Art", "description": "UNESCO site with 127 rock art sites spanning thousands of years.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Senga Bay", "description": "Popular lakeshore resort with fishing villages and water sports.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "1-2 days", "difficulty": "Easy"},
    ],
    "lesotho": [
        {"name": "Sani Pass", "description": "Dramatic mountain pass between South Africa and Lesotho at 2,876m.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Apr", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Thabana Ntlenyana", "description": "Highest peak in southern Africa at 3,482m.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Mar", "duration": "Full day", "difficulty": "Challenging"},
        {"name": "Maletsunyane Falls", "description": "192m single-drop waterfall, one of the highest in southern Africa.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Apr", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Katse Dam", "description": "One of Africa's largest dams in a stunning mountain setting.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Thaba-Bosiu", "description": "Flat-topped mountain fortress of King Moshoeshoe I.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Moderate"},
        {"name": "Afriski Mountain Resort", "description": "Africa's only ski resort in the Maluti Mountains.", "image_url": "", "images": [], "best_time_to_visit": "Jun-Aug", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Sehlabathebe National Park", "description": "Remote UNESCO park with San rock art and alpine scenery.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Apr", "duration": "1-2 days", "difficulty": "Moderate"},
        {"name": "Maseru Market", "description": "Bustling capital market with traditional Basotho blankets and crafts.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Ts'ehlanyane National Park", "description": "Pristine mountain park with indigenous Leucosidea woodlands.", "image_url": "", "images": [], "best_time_to_visit": "Oct-Apr", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Dinosaur Footprints Moyeni", "description": "200-million-year-old dinosaur footprints by the Quthing River.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
    ],
    "eswatini": [
        {"name": "Hlane Royal National Park", "description": "Royal game reserve with lions, elephants and white rhinos.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Mlilwane Wildlife Sanctuary", "description": "Eswatini's oldest protected area with horseback and mountain biking safaris.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Easy"},
        {"name": "Sibebe Rock", "description": "World's largest exposed granite pluton, rising 350m.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Moderate"},
        {"name": "Mantenga Cultural Village", "description": "Traditional Swazi village with cultural performances and waterfall.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Malolotja Nature Reserve", "description": "Pristine wilderness reserve with rare flora and waterfalls.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Full day", "difficulty": "Moderate"},
        {"name": "Ngwenya Mine", "description": "World's oldest mine dating back 43,000 years, with Iron Age museum.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
        {"name": "Swazi Candles Craft Market", "description": "Famous handmade candle factory with artisan craft village.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "1-2 hours", "difficulty": "Easy"},
        {"name": "Mkhaya Game Reserve", "description": "Exclusive Big Five reserve focused on black rhino conservation.", "image_url": "", "images": [], "best_time_to_visit": "May-Oct", "duration": "1-2 days", "difficulty": "Easy"},
        {"name": "Phophonyane Falls", "description": "Beautiful waterfall in lush indigenous forest near Piggs Peak.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "Half day", "difficulty": "Easy"},
        {"name": "Lobamba Royal Village", "description": "Traditional royal and legislative capital with national museum.", "image_url": "", "images": [], "best_time_to_visit": "Year-round", "duration": "2-3 hours", "difficulty": "Easy"},
    ],
}
